  function OnPackageStart()
	local res = LoadPak("pmediumfrontsign", "/pmediumfrontsign/", "../../../OnsetModding/Plugins/pmediumfrontsign/Content")
	res = ReplaceObjectModelMesh(56, "/pmediumfrontsign/pmediumfrontsign")
	local res = LoadPak("psign", "/psign/", "../../../OnsetModding/Plugins/psign/Content")
	res = ReplaceObjectModelMesh(55, "/psign/policesign")
	local res = LoadPak("psmallfrontsign", "/psmallfrontsign/", "../../../OnsetModding/Plugins/psmallfrontsign/Content")
	res = ReplaceObjectModelMesh(54, "/psmallfrontsign/psmallfrontsign")
	local res = LoadPak("pstaarrow", "/pstaarrow/", "../../../OnsetModding/Plugins/pstaarrow/Content")
	res = ReplaceObjectModelMesh(53, "/pstaarrow/pstaarrow")
	local res = LoadPak("pvehonly", "/pvehonly/", "../../../OnsetModding/Plugins/pvehonly/Content")
	res = ReplaceObjectModelMesh(52, "/pvehonly/pvehonly")
end
AddEvent("OnPackageStart", OnPackageStart)
